"""Regenerate the static website changelog from Git history and curated daily highlights."""

from collections import defaultdict
from datetime import date
from html import escape
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
REPO_URL = "https://github.com/anolis/drape"


def git(*args):
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True).strip()


def render():
    if git("rev-parse", "--is-shallow-repository") == "true":
        raise SystemExit("Use a full Git checkout to include the history from the first commit.")
    commits = [
        line.split("\t", 2)
        for line in git("log", "--date=short", "--format=%H%x09%ad%x09%s").splitlines()
    ]
    days = defaultdict(list)
    for commit in commits:
        days[commit[1]].append(commit)
    highlights = json.loads((DOCS / "changelog-highlights.json").read_text())
    homepage = (DOCS / "index.html").read_text()
    # Reuse the website's palette and typography; add only changelog-specific layout rules.
    styles = re.search(r"<style>(.*?)</style>", homepage, re.S).group(1)
    icon = re.search(r'<link rel="icon"[^>]+>', homepage).group(0)
    logo = re.search(r'<a class="logo".*?</a>', homepage, re.S).group(0)
    logo = logo.replace('href="#"', 'href="index.html"')
    entries = []
    for day in sorted(days, reverse=True):
        label = date.fromisoformat(day).strftime("%B %d, %Y").replace(" 0", " ")
        notes = highlights.get(day, {})
        title = notes.get("title", "Updates and fixes")
        changes = "\n".join(f"        <li>{escape(note)}</li>" for note in notes.get("changes", []))
        summary = f'<ul class="changes">\n{changes}\n      </ul>' if changes else ""
        history = "\n".join(
            f'          <li data-commit="{sha}"><a class="commit" href="{REPO_URL}/commit/{sha}">'
            f"{sha[:7]}</a><span>{escape(subject)}</span></li>"
            for sha, _, subject in days[day]
        )
        count = len(days[day])
        entries.append(f'''    <section class="entry" id="day-{day}" aria-labelledby="title-{day}">
      <p class="date"><a href="#day-{day}"><time datetime="{day}">{label}</time></a></p>
      <h2 id="title-{day}">{escape(title)}</h2>
      {summary}
      <details{"" if changes else " open"}>
        <summary>View {count} {"commit" if count == 1 else "commits"}</summary>
        <ol class="commits">
{history}
        </ol>
      </details>
    </section>''')
    first = min(days)
    latest = commits[0][0]
    return f'''<!doctype html>
<!-- Generated by tools/update_changelog.py. Edit changelog-highlights.json for daily highlights. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Changelog — drape</title>
<meta name="description" content="Drape's complete development history: theme manager features, fixes and every commit since {first}.">
{icon}
<style>{styles}
  .changelog {{ max-width: 900px; }}
  .intro {{ padding: 44px 0 12px; }}
  .intro h1 {{ font-size: clamp(36px, 6vw, 54px); line-height: 1.1; margin: 0 0 18px; }}
  .intro .lede {{ margin-bottom: 16px; }}
  .entry {{ padding: 36px 0; border-bottom: 1px solid var(--line); scroll-margin-top: 24px; }}
  .date {{ margin: 0 0 8px; font-size: 14px; font-weight: 600; }}
  .date a {{ color: var(--muted); text-decoration: none; }}
  .entry h2 {{ font-size: clamp(24px, 4vw, 30px); line-height: 1.25; }}
  .changes {{ padding-left: 22px; margin: 20px 0 24px; }}
  .changes li {{ margin-bottom: 12px; }}
  details {{ border: 1px solid var(--line); border-radius: 12px; background: var(--surface); }}
  summary {{ cursor: pointer; padding: 14px 18px; color: var(--accent); font-size: 15px; font-weight: 600; }}
  .commits {{ list-style: none; padding: 0 18px 8px; margin: 0; }}
  .commits li {{ display: flex; align-items: baseline; gap: 12px; padding: 12px 0; border-top: 1px solid var(--line); font-size: 14px; }}
  .commit {{ font-family: ui-monospace, monospace; flex-shrink: 0; }}
  .commits span {{ overflow-wrap: anywhere; }}
  nav {{ display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 10px 20px; }}
  nav a {{ margin-left: 0; }}
  header.top {{ gap: 20px; }}
  a:focus-visible, summary:focus-visible {{ outline: 2px solid var(--accent); outline-offset: 4px; }}
  @media (max-width: 560px) {{ nav {{ gap: 8px 12px; }} nav a {{ margin-left: 0; }} }}
</style>
</head>
<body>
<div class="wrap changelog">
  <header class="top">
    {logo}
    <nav aria-label="Main navigation">
      <a href="index.html">Home</a>
      <a href="index.html#install">Install &amp; update</a>
      <a href="{REPO_URL}">GitHub</a>
    </nav>
  </header>
  <main>
    <div class="intro">
      <h1>Changelog</h1>
      <p class="lede">New features, fixes and the work behind Drape, from the first commit onward. Browse daily highlights, then expand a day to see every commit.</p>
      <p class="note">{len(commits)} commits since <time datetime="{first}">{date.fromisoformat(first).strftime("%B %d, %Y").replace(" 0", " ")}</time>.
        History through <a href="{REPO_URL}/commit/{latest}">{latest[:7]}</a>.
        <a href="{REPO_URL}/commits/main/">View the latest Git history</a>.</p>
      <a class="btn" href="index.html#install">Update your install</a>
    </div>
{chr(10).join(entries)}
  </main>
  <footer>
    <a href="index.html">Back to Drape</a> · <a href="{REPO_URL}">Source code</a> · GPL-3.0
  </footer>
</div>
</body>
</html>
'''


if __name__ == "__main__":
    (DOCS / "changelog.html").write_text(render())
    print("Updated docs/changelog.html from the complete Git history.")
